### PR TITLE
Update library utilities

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

## Summary by Sourcery

Update library utilities with new scripts for example file preparation and ESLint configuration, enhance existing build scripts for better modularity and readability, and improve CSS processing and utility functions.

New Features:
- Introduce a new script `prepExampleFiles.mjs` to remove export statements from example files.
- Add a new ESLint configuration file `eslint.config.mjs` with custom rules.

Enhancements:
- Refactor `generateDocs.mjs` to improve readability and modularity by extracting functions and using path utilities.
- Update `postCss.mjs` to process all CSS files in the directory instead of a single file.
- Enhance `auroLibraryUtils.mjs` by simplifying the `nameExtraction` method and improving JSON parsing.
- Improve `pre-commit.mjs` script formatting.
- Add a template for static styles in `staticStyles-template.js`.

### CODE REVIEW

**Comment by jason-capsule42** [comment]
@sourcery-ai review

**Comment by jason-capsule42** [comment]
https://github.com/sourcery-ai review

**Comment by jason-capsule42** [comment]
@sourcery-ai review

**Review by jordanjones243 — APPROVED** [review]

**Pull request merged**
